from .hospitalSerializer import HospitalSerializer
from .doctorSerializer import DoctorSerializer
from .patientSerializer import PatientSerializer
from .appointmentSerializer_get import AppointmentSerializerGet
from .appointmentSerializer_post import AppointmentSerializerPost