# Generated by Django 3.2.9 on 2021-11-18 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('number', models.CharField(max_length=32, verbose_name='Número')),
                ('speciality', models.CharField(choices=[('', 'None'), ('CD', 'Cardiology')], default='', max_length=2, verbose_name='Especialidade')),
            ],
            options={
                'verbose_name': 'Médico/a',
                'verbose_name_plural': 'Médicos',
                'ordering': ['name', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('health_number', models.IntegerField(verbose_name='Número de saúde')),
                ('gender', models.CharField(choices=[('', 'None'), ('F', 'Female'), ('M', 'Male')], default='', max_length=1, verbose_name='Género')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['name', 'health_number'],
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('doctor', models.ManyToManyField(to='hospital.Doctor', verbose_name='Médicos')),
            ],
            options={
                'verbose_name': 'Hospital',
                'verbose_name_plural': 'Hospitais',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Data')),
                ('local', models.CharField(max_length=255, verbose_name='Gabinete')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospital.doctor', verbose_name='Médico/a')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospital.patient', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'ordering': ['date'],
            },
        ),
    ]
